# Generated by Django 5.2.6 on 2025-10-03 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'xls'])]),
        ),
    ]
