# Generated by Django 5.2.6 on 2025-10-04 14:24

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_pricelist_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', ckeditor.fields.RichTextField()),
                ('phone_number1', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +255 followed by 9 digits.', regex='^\\+255[0-9]{9}$')])),
                ('phone_number2', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must start with +255 followed by 9 digits.', regex='^\\+255[0-9]{9}$')])),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
