# Generated by Django 5.2.6 on 2025-10-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(max_length=200),
        ),
    ]
