# Generated by Django 5.2.6 on 2025-10-05 10:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_address_address_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='heading',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sub_heading',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
