# Generated by Django 5.2.6 on 2025-10-05 10:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_shipment_heading_alter_shipment_sub_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='sub_heading',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
